/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.ModelCompte;
import Models.ModelCompteDao;
import java.awt.Color;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Home extends javax.swing.JFrame {
    

    /**
     * Creates new form Home
     */
    
    ModelCompte mc = new ModelCompte();
    ModelCompteDao mcd = new ModelCompteDao();
    DefaultTableModel model;
    
    public Home() {
        initComponents();
        cree_pane.setVisible(false);
        check_pane.setVisible(false);
        depot_pane.setVisible(false);
        retrait_pane.setVisible(false);
        tableCompte();

        type_choice.add("Courant");
        type_choice.add("Epargne");
        
        
        this.setLocationRelativeTo(null);//se positionner au centre
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_pane = new javax.swing.JPanel();
        sidepan_panel = new javax.swing.JPanel();
        btn_cree_compte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();
        check_btn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        deposit_btn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comming = new javax.swing.JLabel();
        withdraw_btn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        retrait = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        home_btn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        main_title = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cree_pane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        proprio_textfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        numero_textfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        type_choice = new java.awt.Choice();
        save_btn = new javax.swing.JButton();
        home_pane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        compte_table = new javax.swing.JTable();
        check_pane = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        check_textfield = new javax.swing.JTextField();
        btn_verifier_solde = new javax.swing.JButton();
        depot_pane = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        numero2_textfield = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        montant_textfield = new javax.swing.JTextField();
        btn_depot = new javax.swing.JButton();
        retrait_pane = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        numero3_textfield = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        montant2_textfield = new javax.swing.JTextField();
        btn_retrait = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg_pane.setBackground(new java.awt.Color(255, 255, 255));
        bg_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepan_panel.setBackground(new java.awt.Color(53, 33, 89));
        sidepan_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cree_compte.setBackground(new java.awt.Color(64, 43, 100));
        btn_cree_compte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_cree_compteMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/icons8_Create_20px.png"))); // NOI18N

        txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt.setForeground(new java.awt.Color(204, 204, 204));
        txt.setText("Cree compte");
        txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_cree_compteLayout = new javax.swing.GroupLayout(btn_cree_compte);
        btn_cree_compte.setLayout(btn_cree_compteLayout);
        btn_cree_compteLayout.setHorizontalGroup(
            btn_cree_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_cree_compteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        btn_cree_compteLayout.setVerticalGroup(
            btn_cree_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_cree_compteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_cree_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_cree_compteLayout.createSequentialGroup()
                        .addComponent(txt)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_cree_compteLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        sidepan_panel.add(btn_cree_compte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 50));

        check_btn.setBackground(new java.awt.Color(64, 43, 100));
        check_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                check_btnMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/icons8_Plus_Math_20px.png"))); // NOI18N

        text2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        text2.setForeground(new java.awt.Color(204, 204, 204));
        text2.setText("Verfication solde");
        text2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout check_btnLayout = new javax.swing.GroupLayout(check_btn);
        check_btn.setLayout(check_btnLayout);
        check_btnLayout.setHorizontalGroup(
            check_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(check_btnLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        check_btnLayout.setVerticalGroup(
            check_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(check_btnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(check_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, check_btnLayout.createSequentialGroup()
                        .addComponent(text2)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, check_btnLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        sidepan_panel.add(check_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 280, -1));

        deposit_btn.setBackground(new java.awt.Color(64, 43, 100));
        deposit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deposit_btnMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/icons8_Card_Payment_20px.png"))); // NOI18N

        comming.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comming.setForeground(new java.awt.Color(204, 204, 204));
        comming.setText("Depot");
        comming.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                commingMousePressed(evt);
            }
        });

        javax.swing.GroupLayout deposit_btnLayout = new javax.swing.GroupLayout(deposit_btn);
        deposit_btn.setLayout(deposit_btnLayout);
        deposit_btnLayout.setHorizontalGroup(
            deposit_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deposit_btnLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addComponent(comming, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        deposit_btnLayout.setVerticalGroup(
            deposit_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deposit_btnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(deposit_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deposit_btnLayout.createSequentialGroup()
                        .addComponent(comming)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deposit_btnLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        sidepan_panel.add(deposit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        withdraw_btn.setBackground(new java.awt.Color(54, 33, 89));
        withdraw_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                withdraw_btnMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/icons8_Money_Bag_20px.png"))); // NOI18N

        retrait.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        retrait.setForeground(new java.awt.Color(204, 204, 204));
        retrait.setText("Retrait");
        retrait.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retraitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout withdraw_btnLayout = new javax.swing.GroupLayout(withdraw_btn);
        withdraw_btn.setLayout(withdraw_btnLayout);
        withdraw_btnLayout.setHorizontalGroup(
            withdraw_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdraw_btnLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addGap(32, 32, 32)
                .addComponent(retrait, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        withdraw_btnLayout.setVerticalGroup(
            withdraw_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdraw_btnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(withdraw_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdraw_btnLayout.createSequentialGroup()
                        .addComponent(retrait)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdraw_btnLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        sidepan_panel.add(withdraw_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        sidepan_panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("YouBank");
        sidepan_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 135, -1));

        home_btn.setBackground(new java.awt.Color(85, 65, 117));
        home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home_btnMousePressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/icons8_Table_20px_3.png"))); // NOI18N

        txt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt1.setForeground(new java.awt.Color(204, 204, 204));
        txt1.setText("DASHBOARD");
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout home_btnLayout = new javax.swing.GroupLayout(home_btn);
        home_btn.setLayout(home_btnLayout);
        home_btnLayout.setHorizontalGroup(
            home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_btnLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addGap(26, 26, 26)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        home_btnLayout.setVerticalGroup(
            home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_btnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_btnLayout.createSequentialGroup()
                        .addComponent(txt1)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_btnLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        sidepan_panel.add(home_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        bg_pane.add(sidepan_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 550));

        jPanel2.setBackground(new java.awt.Color(110, 89, 222));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Administrations/");

        main_title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        main_title.setForeground(new java.awt.Color(204, 204, 204));
        main_title.setText("Gestion des comptes  ______________________");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(main_title, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(main_title)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        bg_pane.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 750, 160));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("KeeToo");
        bg_pane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 135, -1));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/icons8_Close_Window_30px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        bg_pane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Walter");
        bg_pane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 90, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/icons8_Male_User_30px_2.png"))); // NOI18N
        bg_pane.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 30, 30));

        cree_pane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nom");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Numero");

        numero_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_textfieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Type Compte");

        type_choice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                type_choiceMousePressed(evt);
            }
        });

        save_btn.setText("Enregistrer");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cree_paneLayout = new javax.swing.GroupLayout(cree_pane);
        cree_pane.setLayout(cree_paneLayout);
        cree_paneLayout.setHorizontalGroup(
            cree_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cree_paneLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(cree_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cree_paneLayout.createSequentialGroup()
                        .addGroup(cree_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(type_choice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(proprio_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(cree_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cree_paneLayout.setVerticalGroup(
            cree_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cree_paneLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(cree_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cree_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proprio_textfield)
                    .addComponent(numero_textfield))
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type_choice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        bg_pane.add(cree_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 750, 340));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        compte_table.setForeground(new java.awt.Color(51, 51, 51));
        compte_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ACCOUNT .NO", "NOM", "TYPE", "SOLDE", "ACTION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        compte_table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        compte_table.setRowHeight(25);
        jScrollPane1.setViewportView(compte_table);
        if (compte_table.getColumnModel().getColumnCount() > 0) {
            compte_table.getColumnModel().getColumn(0).setResizable(false);
            compte_table.getColumnModel().getColumn(0).setPreferredWidth(10);
            compte_table.getColumnModel().getColumn(1).setResizable(false);
            compte_table.getColumnModel().getColumn(1).setPreferredWidth(10);
            compte_table.getColumnModel().getColumn(2).setResizable(false);
            compte_table.getColumnModel().getColumn(2).setPreferredWidth(10);
            compte_table.getColumnModel().getColumn(3).setResizable(false);
            compte_table.getColumnModel().getColumn(4).setResizable(false);
            compte_table.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        javax.swing.GroupLayout home_paneLayout = new javax.swing.GroupLayout(home_pane);
        home_pane.setLayout(home_paneLayout);
        home_paneLayout.setHorizontalGroup(
            home_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_paneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        home_paneLayout.setVerticalGroup(
            home_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_paneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        bg_pane.add(home_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 206, 750, 340));

        check_pane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Taper le numero de compte");

        check_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_textfieldActionPerformed(evt);
            }
        });

        btn_verifier_solde.setText("Verifier Solde");
        btn_verifier_solde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verifier_soldeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout check_paneLayout = new javax.swing.GroupLayout(check_pane);
        check_pane.setLayout(check_paneLayout);
        check_paneLayout.setHorizontalGroup(
            check_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(check_paneLayout.createSequentialGroup()
                .addGroup(check_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(check_paneLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(check_paneLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(check_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(check_paneLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(btn_verifier_solde, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        check_paneLayout.setVerticalGroup(
            check_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(check_paneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(check_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_verifier_solde, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        bg_pane.add(check_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 750, 340));

        jLabel16.setText("Numero du compte");

        jLabel17.setText("Montant");

        montant_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montant_textfieldActionPerformed(evt);
            }
        });

        btn_depot.setText("Deposer");
        btn_depot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_depotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout depot_paneLayout = new javax.swing.GroupLayout(depot_pane);
        depot_pane.setLayout(depot_paneLayout);
        depot_paneLayout.setHorizontalGroup(
            depot_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depot_paneLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(depot_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(depot_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(numero2_textfield)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                        .addComponent(montant_textfield))
                    .addComponent(btn_depot, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        depot_paneLayout.setVerticalGroup(
            depot_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depot_paneLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numero2_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(montant_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_depot, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        bg_pane.add(depot_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 750, 340));

        jLabel18.setText("Numero du compte");

        jLabel19.setText("Montant");

        montant2_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montant2_textfieldActionPerformed(evt);
            }
        });

        btn_retrait.setText("Retirer");
        btn_retrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retraitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout retrait_paneLayout = new javax.swing.GroupLayout(retrait_pane);
        retrait_pane.setLayout(retrait_paneLayout);
        retrait_paneLayout.setHorizontalGroup(
            retrait_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(retrait_paneLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(retrait_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(retrait_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(numero3_textfield)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                        .addComponent(montant2_textfield))
                    .addComponent(btn_retrait, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        retrait_paneLayout.setVerticalGroup(
            retrait_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(retrait_paneLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numero3_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(montant2_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_retrait, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        bg_pane.add(retrait_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 750, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
        Login login = new Login();
        
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel11MousePressed

    private void btn_cree_compteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cree_compteMousePressed
        // TODO add your handling code here:
        setColor(btn_cree_compte);
        resetColor(check_btn);
        resetColor(deposit_btn);
        resetColor(home_btn);
        resetColor(withdraw_btn);
        
        home_pane.setVisible(false);
        cree_pane.setVisible(true);
        check_pane.setVisible(false);
        depot_pane.setVisible(false);
        retrait_pane.setVisible(false);

        
        main_title.setText("Creation des comptes  ______________________");
    }//GEN-LAST:event_btn_cree_compteMousePressed

    private void txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMousePressed
        // TODO add your handling code here:
        setColor(btn_cree_compte);
        resetColor(check_btn);
        resetColor(deposit_btn);
        resetColor(home_btn);
        resetColor(withdraw_btn);
        
        home_pane.setVisible(false);
        cree_pane.setVisible(true);
        depot_pane.setVisible(false);
        check_pane.setVisible(false);
        retrait_pane.setVisible(false);
        
        main_title.setText("Creation des comptes  ______________________");
    }//GEN-LAST:event_txtMousePressed

    private void text2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text2MousePressed
        // TODO add your handling code here:
        main_title.setText("Verification de solde  ______________________");
        
        setColor(check_btn);
        resetColor(btn_cree_compte);
        resetColor(deposit_btn);
        resetColor(home_btn);
        resetColor(withdraw_btn);
        
        home_pane.setVisible(false);
        cree_pane.setVisible(false);
        depot_pane.setVisible(false);
        retrait_pane.setVisible(false);
        check_pane.setVisible(true);
        
    }//GEN-LAST:event_text2MousePressed

    private void check_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_btnMousePressed
        // TODO add your handling code here:
        setColor(check_btn);
        resetColor(btn_cree_compte);
        resetColor(deposit_btn);
        resetColor(withdraw_btn);
        
        depot_pane.setVisible(false);
        home_pane.setVisible(false);
        cree_pane.setVisible(false);
        retrait_pane.setVisible(false);
        check_pane.setVisible(true);
        resetColor(home_btn);
        
        main_title.setText("Verification de solde  ______________________");
    }//GEN-LAST:event_check_btnMousePressed

    private void deposit_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deposit_btnMousePressed
        // TODO add your handling code here:
        setColor(deposit_btn);
        resetColor(check_btn);
        resetColor(btn_cree_compte);
        resetColor(home_btn);
        resetColor(withdraw_btn);
        
        home_pane.setVisible(false);
        cree_pane.setVisible(false);
        check_pane.setVisible(false);
        retrait_pane.setVisible(false);
        depot_pane.setVisible(true);
        
        
        main_title.setText("Depot argent  ______________________");
    }//GEN-LAST:event_deposit_btnMousePressed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
       int numero = Integer.valueOf(numero_textfield.getText());
       String proprio = proprio_textfield.getText();
       String type = type_choice.getSelectedItem();
       int solde = 0;
       
       mc.setNumero(numero);
       mc.setProprio(proprio);
       mc.setType(type);
       mc.setSolde(solde);
       
       mcd.Enregistrer(mc);
       
       tableCompte();
       actualiser();
       tableActualiser();

    }//GEN-LAST:event_save_btnActionPerformed

    private void tableActualiser(){
        
        model = (DefaultTableModel) compte_table.getModel();
        
        for(int i=0;i<model.getRowCount();i++){
            model.removeRow(i);
            i = i-1;
        }
    }
    
    private void actualiser(){
        proprio_textfield.setText("");
        numero_textfield.setText("");
    }
    
    private void tableCompte(){
        List<ModelCompte> list = mcd.Liste();
        
        model = (DefaultTableModel) compte_table.getModel();
        
        Object[] obj = new Object[5];
        
        for(int i=0; i<list.size();i++){
            obj[0]=list.get(i).getNumero();
            obj[1]=list.get(i).getProprio();
            obj[2]=list.get(i).getType();
            obj[3]=list.get(i).getSolde();
            obj[4]= ""; 
            
            model.addRow(obj);
            
        }
        
    }
    
    private void numero_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_textfieldActionPerformed

    private void type_choiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_type_choiceMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_type_choiceMousePressed

    private void txt1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MousePressed
        // TODO add your handling code here:
        main_title.setText("Gestion des comptes  ______________________");
        
        tableActualiser();
        tableCompte();
        
        home_pane.setVisible(true);
        cree_pane.setVisible(false);
        depot_pane.setVisible(false);
        check_pane.setVisible(false);
        retrait_pane.setVisible(false);
        
        setColor(home_btn);
        resetColor(btn_cree_compte);
        resetColor(check_btn);
        resetColor(deposit_btn);
        resetColor(withdraw_btn);
    }//GEN-LAST:event_txt1MousePressed

    private void home_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMousePressed
        // TODO add your handling code here:
        main_title.setText("Gestion des comptes  ______________________");
        
        tableActualiser();
        tableCompte();
        
        
        home_pane.setVisible(true);
        cree_pane.setVisible(false);
        depot_pane.setVisible(false);
        check_pane.setVisible(false);
        retrait_pane.setVisible(false);
        
        setColor(home_btn);
        resetColor(btn_cree_compte);
        resetColor(check_btn);
        resetColor(deposit_btn);
        resetColor(withdraw_btn);
    }//GEN-LAST:event_home_btnMousePressed

    private void commingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commingMousePressed
        // TODO add your handling code here:
        main_title.setText("Depot argent  ______________________");
        
        setColor(deposit_btn);
        resetColor(check_btn);
        resetColor(btn_cree_compte);
        resetColor(home_btn);
        resetColor(withdraw_btn);
        
        home_pane.setVisible(false);
        cree_pane.setVisible(false);
        check_pane.setVisible(false);
        retrait_pane.setVisible(false);
        depot_pane.setVisible(true);
    }//GEN-LAST:event_commingMousePressed

    private void check_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_textfieldActionPerformed

    private void btn_verifier_soldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verifier_soldeActionPerformed
        // TODO add your handling code here:
        
        int numero = Integer.valueOf(check_textfield.getText());
        
        ModelCompteDao.VerifierSolde(numero);
    }//GEN-LAST:event_btn_verifier_soldeActionPerformed

    private void montant_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montant_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montant_textfieldActionPerformed

    private void btn_depotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_depotActionPerformed
        // TODO add your handling code here:
        
        int numero = Integer.valueOf(numero2_textfield.getText());
        int montant = Integer.valueOf(montant_textfield.getText());
        
        numero2_textfield.setText("");
        montant_textfield.setText("");
        
        ModelCompteDao.depot(montant, numero);
        
    }//GEN-LAST:event_btn_depotActionPerformed

    private void montant2_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montant2_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montant2_textfieldActionPerformed

    private void btn_retraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retraitActionPerformed
        // TODO add your handling code here:
        
        int numero = Integer.valueOf(numero3_textfield.getText());
        int montant = Integer.valueOf(montant2_textfield.getText());
        
        numero3_textfield.setText("");
        montant2_textfield.setText("");
        
        ModelCompteDao.retrait(montant, numero);
        
    }//GEN-LAST:event_btn_retraitActionPerformed

    private void withdraw_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdraw_btnMousePressed
        // TODO add your handling code here:
        
        main_title.setText("Retrait argent  ______________________");
        
        setColor(withdraw_btn);
        resetColor(deposit_btn);
        resetColor(check_btn);
        resetColor(btn_cree_compte);
        resetColor(home_btn);
        
        home_pane.setVisible(false);
        cree_pane.setVisible(false);
        check_pane.setVisible(false);
        retrait_pane.setVisible(true);
        depot_pane.setVisible(false);
        
    }//GEN-LAST:event_withdraw_btnMousePressed

    private void retraitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retraitMousePressed
        // TODO add your handling code here:
        
        main_title.setText("Retrait argent  ______________________");
        
        setColor(withdraw_btn);
        resetColor(deposit_btn);
        resetColor(check_btn);
        resetColor(btn_cree_compte);
        resetColor(home_btn);
        
        home_pane.setVisible(false);
        cree_pane.setVisible(false);
        check_pane.setVisible(false);
        retrait_pane.setVisible(true);
        depot_pane.setVisible(false);
               
    }//GEN-LAST:event_retraitMousePressed

    /**
     * @param args the command line arguments
     */
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,118));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(64,43,100));
    }
    
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    private void loggout_btnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        Login login = new Login();
        
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        this.dispose();
    }
    
    public void setLoggedUserName(String name){
//        loggeduser_label.setName(name);
//        loggeduser_label.setText(name);
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_pane;
    private javax.swing.JPanel btn_cree_compte;
    private javax.swing.JButton btn_depot;
    private javax.swing.JButton btn_retrait;
    private javax.swing.JButton btn_verifier_solde;
    private javax.swing.JPanel check_btn;
    private javax.swing.JPanel check_pane;
    private javax.swing.JTextField check_textfield;
    private javax.swing.JLabel comming;
    private javax.swing.JTable compte_table;
    private javax.swing.JPanel cree_pane;
    private javax.swing.JPanel deposit_btn;
    private javax.swing.JPanel depot_pane;
    private javax.swing.JPanel home_btn;
    private javax.swing.JPanel home_pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel main_title;
    private javax.swing.JTextField montant2_textfield;
    private javax.swing.JTextField montant_textfield;
    private javax.swing.JTextField numero2_textfield;
    private javax.swing.JTextField numero3_textfield;
    private javax.swing.JTextField numero_textfield;
    private javax.swing.JTextField proprio_textfield;
    private javax.swing.JLabel retrait;
    private javax.swing.JPanel retrait_pane;
    private javax.swing.JButton save_btn;
    private javax.swing.JPanel sidepan_panel;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txt1;
    private java.awt.Choice type_choice;
    private javax.swing.JPanel withdraw_btn;
    // End of variables declaration//GEN-END:variables

}
